# https://github.com/actions/setup-python#caching-packages-dependencies
name: Continuous Integration
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened]
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py: ["python:3.11", "python:3.10", "python:3.9"]
    name: ${{ matrix.python-version }} testing & linters
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        id: pyver
        with:
          python-version: ${{ matrix.py }}
          check-latest: true
          cache: 'poetry'
      - name: ${{ steps.pyver.outputs.python-version }}
        run: python --version
      - run: poetry install --no-interaction --sync
      - run: poetry run tox --recreate